name: build release binaries

on:
  pull_request:
  release:
    types: [created]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install gettext
      - uses: actions/checkout@v2
      - name: build mecab
        run: |
          ./autogen.sh
          ./configure
          make all
          sudo make install
          make dist
          mkdir -p ../dist/mecab/
          mv mecab-*.tar.gz ../dist/mecab/
        working-directory: mecab
      - name: build ipadic
        run: |
          ./autogen.sh
          ./configure
          make dist
          mkdir -p ../dist/mecab-ipadic/
          mv mecab-ipadic-*.tar.gz ../dist/mecab-ipadic/
        working-directory: mecab-ipadic
      - name: build jumandic
        run: |
          ./autogen.sh
          ./configure
          make dist
          mkdir -p ../dist/mecab-jumandic/
          mv mecab-jumandic-*.tar.gz ../dist/mecab-jumandic/
        working-directory: mecab-jumandic
      - uses: actions/upload-artifact@v1
        with:
          name: dist
          path: dist
      - name: Upload Release Assets
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: |
            dist/**/*.tar.gz
        if: github.event_name == 'release'

  windows:
    name: windows
    runs-on: windows-latest
    needs: build
    strategy:
      fail-fast: false
      matrix:
        machine:
          - x64
          - x86
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v1
        with:
          name: dist
      - name: untar
        run: |
          tar xzvf mecab-*.tar.gz
          rm mecab-*.tar.gz
          mv mecab-*/* .
        shell: bash
        working-directory: dist/mecab
      - name: build
        run: call .github\build-windows.bat
        shell: cmd
        env:
          BUILD_TYPE: ${{ matrix.machine }}
