name: Update Documents

on:
  pull_request: {}
  push: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install hugo
        run: |
          curl -sSL https://github.com/gohugoio/hugo/releases/download/v0.62.2/hugo_0.62.2_Linux-64bit.tar.gz > hugo.tar.gz
          tar xf hugo.tar.gz
          sudo mv hugo /usr/local/bin/
      - name: install doxygen help2man man2html
        run: sudo apt-get install doxygen help2man man2html gettext
      - name: generate documents
        run: .github/update-docs.sh
      - run: |
          git config --global user.name "Ichinose Shogo"
          git config --global user.email shogo82148@gmail.com
          git add docs mecab/doc mecab/man
          git commit -m "auto generate documents $(date +"%Y-%m-%d %H:%M:%S")" || ( echo "no updates" && exit 0 )
          if [[ "$GITHUB_EVENT_NAME" = "push" ]] && [[ "$GITHUB_REF" = "refs/heads/master" ]]; then
            git push origin master
          fi
